// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("debugscraper")
	ScopeName = "go.opentelemetry.io/collector/receiver/debugscraper"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
