// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("httpscrapercontroller")
	ScopeName = "go.opentelemetry.io/collector/extension/xextension/scrapercontroller/httpscrapercontroller"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
